### ISSUE TITLE
Option to disable gravity

### ISSUE THREAD

**Issue by cernael** [themoritz/txgraph#19]
I would like to be able to fine-tune the layout of a certain graph for screenshot purposes, and it would be useful to entirely disable the dynamic layout adjustments when I do that instead of trying to tweak the layout params hoping the best layout emerges from that. Might be as easy as allowing Speed to equal 0.

**Comment by themoritz** [comment]
This is deployed and works as follows:

<img width="335" alt="Screenshot 2024-08-10 at 14 49 49" src="https://github.com/user-attachments/assets/d1c3adb4-d797-41fd-bfaa-38fb31b5840f">
