### ISSUE TITLE
API request  failed message when trying to load any TX

### ISSUE THREAD

**Issue by Valadaress** [themoritz/txgraph#22]
Do you support the https://txgraph.info/ website? When I try to load any transaction, including the examples, I get the following error:

![image](https://github.com/user-attachments/assets/ec6f7b47-0ecd-430d-b5eb-71fb241c3f51)

**Comment by themoritz** [comment]
Thanks for bringing this to my attention! There were some disk space issues on the server (blockchain is growing) which I fixed. The API should be working as soon as the bitcoin daemon is synced again (maybe half an hour).

**Comment by themoritz** [comment]
Works again.
